# Generated by Django 2.1.7 on 2019-02-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practoapp', '0002_interactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactions',
            name='count',
            field=models.BooleanField(default=True),
        ),
    ]
