# Generated by Django 2.1.7 on 2019-02-18 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practoapp', '0003_auto_20190218_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interactions',
            old_name='doctor_id',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='interactions',
            old_name='user_id',
            new_name='user',
        ),
    ]
