# Generated by Django 2.1.7 on 2019-02-19 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practoapp', '0004_auto_20190218_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interactions',
            old_name='count',
            new_name='is_liked',
        ),
    ]
